# Generated by Django 4.2.5 on 2023-09-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_SOFTDESK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('PYTHON', 'Python3'), ('DJANGO', 'DJANGO'), ('REACT', 'React'), ('BACKEND', 'Back-end'), ('FRONTEND', 'Front-end'), ('IOS', 'IOS'), ('ANDROID', 'Android')], max_length=255),
        ),
    ]
